//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контр.
    /// </summary>
    // *** Start programmer edit section *** (контр CustomAttributes)

    // *** End programmer edit section *** (контр CustomAttributes)
    [AutoAltered()]
    [Caption("Контр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("контрE", new string[] {
            "когнтра as \'Когнтра\'"})]
    [View("контрL", new string[] {
            "когнтра as \'Когнтра\'"})]
    public class контр : ICSSoft.STORMNET.DataObject
    {
        
        private string fкогнтра;
        
        // *** Start programmer edit section *** (контр CustomMembers)

        // *** End programmer edit section *** (контр CustomMembers)

        
        /// <summary>
        /// когнтра.
        /// </summary>
        // *** Start programmer edit section *** (контр.когнтра CustomAttributes)

        // *** End programmer edit section *** (контр.когнтра CustomAttributes)
        [StrLen(255)]
        public virtual string когнтра
        {
            get
            {
                // *** Start programmer edit section *** (контр.когнтра Get start)

                // *** End programmer edit section *** (контр.когнтра Get start)
                string result = this.fкогнтра;
                // *** Start programmer edit section *** (контр.когнтра Get end)

                // *** End programmer edit section *** (контр.когнтра Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (контр.когнтра Set start)

                // *** End programmer edit section *** (контр.когнтра Set start)
                this.fкогнтра = value;
                // *** Start programmer edit section *** (контр.когнтра Set end)

                // *** End programmer edit section *** (контр.когнтра Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "контрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View контрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("контрE", typeof(IIS.Test.контр));
                }
            }
            
            /// <summary>
            /// "контрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View контрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("контрL", typeof(IIS.Test.контр));
                }
            }
        }
    }
}
