//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ном.
    /// </summary>
    // *** Start programmer edit section *** (ном CustomAttributes)

    // *** End programmer edit section *** (ном CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("номE", new string[] {
            "нома as \'Нома\'",
            "контр as \'Контр\'",
            "контр.когнтра as \'Когнтра\'"}, Hidden=new string[] {
            "контр.когнтра"})]
    [MasterViewDefineAttribute("номE", "контр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "когнтра")]
    [View("номL", new string[] {
            "нома as \'Нома\'",
            "контр.когнтра as \'Когнтра\'"})]
    public class ном : ICSSoft.STORMNET.DataObject
    {
        
        private string fнома;
        
        private IIS.Test.контр fконтр;
        
        // *** Start programmer edit section *** (ном CustomMembers)

        // *** End programmer edit section *** (ном CustomMembers)

        
        /// <summary>
        /// нома.
        /// </summary>
        // *** Start programmer edit section *** (ном.нома CustomAttributes)

        // *** End programmer edit section *** (ном.нома CustomAttributes)
        [StrLen(255)]
        public virtual string нома
        {
            get
            {
                // *** Start programmer edit section *** (ном.нома Get start)

                // *** End programmer edit section *** (ном.нома Get start)
                string result = this.fнома;
                // *** Start programmer edit section *** (ном.нома Get end)

                // *** End programmer edit section *** (ном.нома Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ном.нома Set start)

                // *** End programmer edit section *** (ном.нома Set start)
                this.fнома = value;
                // *** Start programmer edit section *** (ном.нома Set end)

                // *** End programmer edit section *** (ном.нома Set end)
            }
        }
        
        /// <summary>
        /// ном.
        /// </summary>
        // *** Start programmer edit section *** (ном.контр CustomAttributes)

        // *** End programmer edit section *** (ном.контр CustomAttributes)
        [PropertyStorage(new string[] {
                "контр"})]
        [NotNull()]
        public virtual IIS.Test.контр контр
        {
            get
            {
                // *** Start programmer edit section *** (ном.контр Get start)

                // *** End programmer edit section *** (ном.контр Get start)
                IIS.Test.контр result = this.fконтр;
                // *** Start programmer edit section *** (ном.контр Get end)

                // *** End programmer edit section *** (ном.контр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ном.контр Set start)

                // *** End programmer edit section *** (ном.контр Set start)
                this.fконтр = value;
                // *** Start programmer edit section *** (ном.контр Set end)

                // *** End programmer edit section *** (ном.контр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "номE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View номE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("номE", typeof(IIS.Test.ном));
                }
            }
            
            /// <summary>
            /// "номL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View номL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("номL", typeof(IIS.Test.ном));
                }
            }
        }
    }
}
