//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тест.
    /// </summary>
    // *** Start programmer edit section *** (тест CustomAttributes)

    // *** End programmer edit section *** (тест CustomAttributes)
    [AutoAltered()]
    [Caption("Тест")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("тестE", new string[] {
            "ХЗ as \'ХЗ\'",
            "ном as \'Ном\'",
            "ном.нома as \'Нома\'",
            "ном.контр.когнтра as \'когнтра\'"}, Hidden=new string[] {
            "ном.нома"})]
    [MasterViewDefineAttribute("тестE", "ном", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "нома")]
    [View("тестL", new string[] {
            "ХЗ as \'ХЗ\'",
            "ном.нома as \'Нома\'"})]
    public class тест : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Test.хуй fХЗ;
        
        private IIS.Test.ном fном;
        
        // *** Start programmer edit section *** (тест CustomMembers)

        // *** End programmer edit section *** (тест CustomMembers)

        
        /// <summary>
        /// ХЗ.
        /// </summary>
        // *** Start programmer edit section *** (тест.ХЗ CustomAttributes)

        // *** End programmer edit section *** (тест.ХЗ CustomAttributes)
        public virtual IIS.Test.хуй ХЗ
        {
            get
            {
                // *** Start programmer edit section *** (тест.ХЗ Get start)

                // *** End programmer edit section *** (тест.ХЗ Get start)
                IIS.Test.хуй result = this.fХЗ;
                // *** Start programmer edit section *** (тест.ХЗ Get end)

                // *** End programmer edit section *** (тест.ХЗ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (тест.ХЗ Set start)

                // *** End programmer edit section *** (тест.ХЗ Set start)
                this.fХЗ = value;
                // *** Start programmer edit section *** (тест.ХЗ Set end)

                // *** End programmer edit section *** (тест.ХЗ Set end)
            }
        }
        
        /// <summary>
        /// Тест.
        /// </summary>
        // *** Start programmer edit section *** (тест.ном CustomAttributes)

        // *** End programmer edit section *** (тест.ном CustomAttributes)
        [PropertyStorage(new string[] {
                "ном"})]
        [NotNull()]
        public virtual IIS.Test.ном ном
        {
            get
            {
                // *** Start programmer edit section *** (тест.ном Get start)

                // *** End programmer edit section *** (тест.ном Get start)
                IIS.Test.ном result = this.fном;
                // *** Start programmer edit section *** (тест.ном Get end)

                // *** End programmer edit section *** (тест.ном Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (тест.ном Set start)

                // *** End programmer edit section *** (тест.ном Set start)
                this.fном = value;
                // *** Start programmer edit section *** (тест.ном Set end)

                // *** End programmer edit section *** (тест.ном Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "тестE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View тестE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("тестE", typeof(IIS.Test.тест));
                }
            }
            
            /// <summary>
            /// "тестL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View тестL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("тестL", typeof(IIS.Test.тест));
                }
            }
        }
    }
}
