//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Хуй.
    /// </summary>
    // *** Start programmer edit section *** (хуй CustomAttributes)

    // *** End programmer edit section *** (хуй CustomAttributes)
    public enum хуй
    {
        
        // *** Start programmer edit section *** (хуй.хуй1 CustomAttributes)

        // *** End programmer edit section *** (хуй.хуй1 CustomAttributes)
        хуй1,
        
        // *** Start programmer edit section *** (хуй.хуй2 CustomAttributes)

        // *** End programmer edit section *** (хуй.хуй2 CustomAttributes)
        хуй2,
    }
}
